export type UiLocale = "hi" | "en";

export const LOCALE_STORAGE_KEY = "shopsaathi-ui-locale";

/** Flat copy: each key has hi (default Hinglish UI) and en. */
export const UI_STRINGS = {
  navHome: { hi: "Home", en: "Home" },
  navBilling: { hi: "Billing", en: "Billing" },
  navUdhar: { hi: "Udhar", en: "Credit" },
  navInventory: { hi: "Stock", en: "Stock" },
  navMore: { hi: "Aur", en: "More" },
  navSubHome: { hi: "घर", en: "" },
  navSubBilling: { hi: "बिलिंग", en: "" },
  navSubUdhar: { hi: "उधार", en: "" },
  navSubInventory: { hi: "स्टॉक", en: "" },
  navSubMore: { hi: "और", en: "" },

  languageHeading: { hi: "App ki bhasha", en: "App language" },
  languageHint: {
    hi: "English ya Hindi — poori app yahi dikhegi",
    en: "Choose English or Hindi for the whole app",
  },
  langEnglish: { hi: "English", en: "English" },
  langHindi: { hi: "हिंदी", en: "Hindi" },

  billingHeading: { hi: "Naya Bill", en: "New bill" },
  billingSub: { hi: "ShopSaathi — fast billing", en: "ShopSaathi — fast billing" },
  searchPlaceholder: {
    hi: "Item ka naam likho...",
    en: "Type item name…",
  },
  noMatch: { hi: "Koi item nahi mila — naam check karo", en: "No match — check spelling" },
  emptyInventoryHint: {
    hi: "Apne products inventory mein add karo",
    en: "Add products in Stock first",
  },
  searchAddBillSuffix: { hi: "bill mein daalo", en: "add to bill" },
  searchNotFoundAddFooter: {
    hi: "Nahi mila? Naya add karo",
    en: "Not listed? Add new",
  },
  customItemTitle: { hi: "Bill par naya item", en: "Add line to bill" },
  customItemSubtitle: {
    hi: "Naam, daam (₹), kitni — inventory mein save nahi hoga",
    en: "Name, price (₹), qty — not saved to your stock list",
  },
  customItemName: { hi: "Item ka naam", en: "Item name" },
  customItemPrice: { hi: "Ek ka daam (₹)", en: "Price each (₹)" },
  customItemQty: { hi: "Kitni piece / qty", en: "Quantity" },
  customItemAdd: { hi: "Bill mein daalo", en: "Add to bill" },
  billItems: { hi: "Bill items", en: "Bill items" },
  linesCount: { hi: "lines", en: "lines" },
  emptyCart: {
    hi: "Upar se item chuno — yahan list dikhegi",
    en: "Pick items above — they appear here",
  },
  increaseStock: { hi: "+ Stock badhao", en: "Add stock" },
  decreaseStock: { hi: "− Stock ghatao", en: "Remove stock" },
  grandTotal: { hi: "Kul Total", en: "Grand total" },
  gstCheckbox: { hi: "+18% GST", en: "+18% GST" },
  gstBreakdown: { hi: "GST", en: "GST" },
  withoutGst: { hi: "Without GST", en: "Before GST" },
  discountLabel: { hi: "Discount (₹)", en: "Discount (₹)" },
  discountHint: {
    hi: "Bill se kaatne ke liye rakam",
    en: "Flat amount off items (before GST)",
  },
  afterDiscount: { hi: "Discount ke baad", en: "After discount" },
  editRate: { hi: "Daam set", en: "Set price" },
  rateSheetTitle: { hi: "Item ka daam (₹)", en: "Item price (₹)" },
  rateSave: { hi: "Theek hai", en: "OK" },
  cashBill: { hi: "Cash Bill Karo", en: "Cash bill" },
  udharBill: { hi: "Udhar Mein Daalo", en: "Add to credit" },
  saving: { hi: "Saving…", en: "Saving…" },
  loading: { hi: "Loading…", en: "Loading…" },
  aiBadge: { hi: "AI", en: "AI" },
  doneTitle: { hi: "Ho gaya ✓", en: "Done ✓" },
  doneCash: { hi: "Cash bill", en: "Cash bill saved" },
  doneUdhar: { hi: "Udhar mein daala gaya", en: "Saved on credit" },
  subtotal: { hi: "Subtotal", en: "Subtotal" },
  gstLine: { hi: "GST 18%", en: "GST 18%" },
  finalTotal: { hi: "Kul Total", en: "Total" },
  discountLine: { hi: "Discount", en: "Discount" },
  whatsappShare: { hi: "WhatsApp par bhejo", en: "Share on WhatsApp" },
  newBill: { hi: "Naya Bill", en: "New bill" },
  planLimitTitle: {
    hi: "Aapka free plan ka 30 bills limit aa gaya! 🚫",
    en: "Free plan: 30 bills this month — limit reached 🚫",
  },
  planLimitBody: {
    hi: "Is mahine aur bill nahi bana sakte. Upgrade karo ₹199/month mein unlimited bills ke liye.",
    en: "No more bills on the free plan this month. Upgrade for unlimited bills.",
  },
  upgrade: { hi: "Upgrade Karo", en: "Upgrade" },
  freePlanBanner: { hi: "Free Plan:", en: "Free plan:" },
  billsUsedSuffix: { hi: "bills used this month", en: "bills used this month" },
  saveFailed: { hi: "Save nahi ho paya — dubara try karo.", en: "Could not save — try again." },
  udharCustomerTitle: { hi: "Customer ka naam", en: "Customer name" },
  udharCustomerSub: { hi: "Udhar bill ke liye", en: "For credit bill" },
  nameLabel: { hi: "Naam", en: "Name" },
  udharPlaceholder: { hi: "Jaise: Ramesh Verma", en: "e.g. Ramesh Verma" },
  saveBill: { hi: "Save bill", en: "Save bill" },
  cancel: { hi: "Cancel", en: "Cancel" },
  removeItem: { hi: "Hatao", en: "Remove" },
  decreaseQty: { hi: "Kam", en: "Less" },
  increaseQty: { hi: "Zyada", en: "More" },
  billingSlash: { hi: "Billing / बिलिंग", en: "Billing" },

  invHeading: { hi: "Inventory / स्टॉक", en: "Stock / inventory" },
  invSub: { hi: "ShopSaathi — maal ka hisaab", en: "ShopSaathi — stock" },
  invTotalItems: { hi: "Kul Items", en: "Total items" },
  invLowStock: { hi: "Kam Stock", en: "Low stock" },
  invLowHint: { hi: "qty < 5", en: "qty < 5" },
  invSearchPh: { hi: "Product dhundo...", en: "Search product…" },
  invStock: { hi: "Stock", en: "Stock" },
  invPrice: { hi: "Price / unit", en: "Price / unit" },
  invLowBadge: { hi: "Kam Stock", en: "Low stock" },
  invEditTitle: { hi: "Product edit", en: "Edit product" },
  invEditSub: { hi: "Naam, daam, stock update", en: "Name, price, stock" },
  invQty: { hi: "Quantity", en: "Quantity" },
  invSave: { hi: "Save", en: "Save" },
  invSaveProduct: { hi: "Product save", en: "Save product" },
  invAddTitle: { hi: "Naya product", en: "New product" },
  invAddSub: { hi: "Naam, price, qty, category", en: "Name, price, qty, category" },
  invClose: { hi: "Band karo", en: "Close" },

  homeTagline: { hi: "दुकान का साथी", en: "Your shop companion" },
  homeWelcome: { hi: "Namaste 👋", en: "Hello 👋" },
  homeWelcomeSub: {
    hi: "Welcome — आपकी दुकान, आसान प्रबंधन",
    en: "Welcome — simple shop management",
  },
  homeTodaySales: { hi: "Aaj ki Kamai", en: "Today's sales" },
  homeTodaySalesSub: { hi: "आज की बिक्री (bills)", en: "Today's total (bills)" },
  homeUdharTotal: { hi: "Kul Udhar", en: "Total credit" },
  homeUdharSub: { hi: "बकाया जोड़", en: "Outstanding" },
  homeBillsToday: { hi: "Aaj ke Bills", en: "Bills today" },
  homeBillsTodaySub: { hi: "आज के बिल", en: "Count" },
  homeLowStock: { hi: "Kam Stock", en: "Low stock" },
  homeLowStockSub: { hi: "stock < 5", en: "Items with stock < 5" },
  homeRecentBills: { hi: "Haal ke Bills", en: "Recent bills" },
  homeNoBills: {
    hi: "Abhi koi bill nahi — pehla bill banayein",
    en: "No bills yet — create your first",
  },
  homeQuick: { hi: "Quick actions", en: "Quick actions" },
  qaBillTitle: { hi: "Naya bill", en: "New bill" },
  qaBillSub: { hi: "नया बिल", en: "Open billing" },
  qaUdharTitle: { hi: "Udhar jodo", en: "Add credit" },
  qaUdharSub: { hi: "उधार खाता", en: "Credit ledger" },
  qaReportsTitle: { hi: "Reports dekho", en: "Reports" },
  qaReportsSub: { hi: "रिपोर्ट", en: "Sales summary" },
  homeUpgradeHint: {
    hi: "Free plan limit khatam hone wala hai. Upgrade karke unlimited bills pao.",
    en: "You are close to the free plan limit. Upgrade for unlimited bills.",
  },
  homeInsights: { hi: "Insights ✨", en: "Insights ✨" },
  cash: { hi: "Cash", en: "Cash" },
  udhar: { hi: "Udhar", en: "Credit" },
} as const;

export type UiStringKey = keyof typeof UI_STRINGS;
